co:
  vacancies:
    - chamber: lower
      district: 6
      vacant_until: 2020-03-01
ct:
  vacancies:
    - chamber: lower
      district: 39
      vacant_until: 2021-01-01
    - chamber: lower
      district: 99
      vacant_until: 2021-01-01
    - chamber: upper
      district: 3
      vacant_until: 2021-01-01
    - chamber: upper
      district: 5
      vacant_until: 2021-01-01
    - chamber: upper
      district: 6
      vacant_until: 2021-01-01
il:
  vacancies:
    - chamber: upper
      district: 11
      vacant_until: 2020-05-01
ma:
  vacancies:
    - chamber: upper
      district: Plymouth and Barnstable
      vacant_until: 2020-05-01
    - chamber: upper
      district: Second Hampden and Hampshire
      vacant_until: 2020-05-01
    - chamber: lower
      district: Third Bristol
      vacant_until: 2020-05-01
    - chamber: lower
      district: Thirty-Second Middlesex
      vacant_until: 2020-05-01
    - chamber: lower
      district: Thirty-Seventh Middlesex
      vacant_until: 2020-05-01
mo:
  vacancies:
    - chamber: upper
      district: 3
      vacant_until: 2021-01-01
    - chamber: upper
      district: 7
      vacant_until: 2021-01-01
    - chamber: upper
      district: 9
      vacant_until: 2021-01-01
    - chamber: lower
      district: 34
      vacant_until: 2021-01-01
nc:
  vacancies:
      - chamber: upper
        district: 7
        vacant_until: 2021-01-01
nj:
  vacancies:
      - chamber: lower
        district: 25
        vacant_until: 2020-03-01
pa:
  vacancies:
    - chamber: upper
      district: 48
      vacant_until: 2021-01-01

parties:
 - Democratic
 - Democratic-Farmer-Labor    # MN
 - Democratic/Progressive     # VT
 - Independent
 - Libertarian
 - Nonpartisan
 - Partido Independentista Puertorriqueño
 - Partido Nuevo Progresista
 - Partido Popular Democrático
 - Progressive
 - Progressive/Democratic    # VT
 - Republican
 - Green
 - Republican/Democratic     # VT
 - Carter County Republican  # TN
